name = "TimestepperTestCases"
uuid = "8d628e06-8e8e-46bb-a074-537775fcc231"
version = "1.0.0-DEV"
authors = ["Simone Silvestri <silvestri.simone0@gmail.com> and contributors"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CairoMakie = "0.14.0"
JLD2 = "0.6.2"
KernelAbstractions = "0.9.38"
Oceananigans = "0.100.3"
Printf = "1.10, 1.11"
Random = "1.10, 1.11"
Statistics = "1.10, 1.11"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
